
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="content-contact">
    <div class="page-title">
        <h1>Formulario de Cambio y Devolución</h1>
    </div>
    <div class="form_cambio_valkymia">
        <form action="<?php echo $this->getFormAction(); ?>" id="formulariocambioForm" method="post" class="scaffold-form">
            <div class="fieldset">
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <label for="name" class="required"><em>*</em><?php echo $this->__('Name') ?></label>
                            <div class="input-box">
                                <input name="name" id="name" title="<?php echo $this->__('Name') ?>" value="<?php echo $this->htmlEscape(Mage::helper('formulariocambio')->getUserName()) ?>" class="required-entry input-text" type="text" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="name" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
                            <div class="input-box">
                                <input name="lastname" id="lastname" title="<?php echo $this->__('LastName') ?>" value="" class="required-entry input-text" type="text" />
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="field">
                            <label for="telephone"><?php echo $this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input name="telephone" id="telephone" title="<?php echo $this->__('Telephone') ?>" value="" class="input-text" type="tel" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                            <div class="input-box">
                                <input name="email" id="email" title="<?php echo $this->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
                            </div>
                        </div>
                    </li>
                    <li class="wide">
                        <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                        <div class="input-box">
                            <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="buttons">
                <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
            </div>
        </form>
    </div>
</div>


<script type="text/javascript">
    var magazineForm = new VarienForm('formulariocambioForm', true);
</script>